// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// const SUPABASE_URL = "https://cemlsefaiamdbjckzzng.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlbWxzZWZhaWFtZGJqY2t6em5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzAyOTIsImV4cCI6MjA3Mzk0NjI5Mn0.n4WeqvajvFGxs1NZChsjl47BgNrnWxUALnTVLNCbFy8";
const SUPABASE_URL = "https://kouzruxnyurjxqwdkijo.supabase.co";

// ⚠️ ERRROR FIX: Supabase keys ALWAYS start with `eyJ...` (it is a long JWT token).
// Aapne jo `sb_publishable_...` daala hai, wo invalid format hai, isliye "No API key found" ka error aa raha hai.
// Supabase Dashboard > Settings > API > 'anon' public key copy karein aur yahan paste karein:
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvdXpydXhueXVyanhxd2RraWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMjM0NTgsImV4cCI6MjA5MDY5OTQ1OH0.KWmRMcRousQXyIkcM8ofsEaB0-kHPcRb3lJuLRsBulI";



// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});